### ISSUE TITLE
Communications platforms

### ISSUE THREAD

**Issue by kastyr1984** [MacroTeam/FFBE-Macros#23]
So commenting on issues and pull requests makes for a poor method of primary communication. There's a lot of email spam and it's difficult to keep our threads in check. I would propose that we get folks onto a Slack channel, but we've also already been invited onto at least one FFBE based Discord channel. Both of these seem pretty cross platform, I only suggest Slack because I already use it for communication in two other areas of my life and it's nice to keep things simple.

What are y'all's thoughts on this issue?

**Comment by Kawoxux** [comment]
Discord invite was for my own server and that's defo my preference. I have discord on both work and personal phones so can always access it. Plus can direct share screenies etc very swiftly. Never used slack before which is why discord gets my vote

Sent from my Sony Xperia™ smartphone

---- kastyr wrote ----


So commenting on issues and pull requests makes for a poor method of primary communication. There's a lot of email spam and it's difficult to keep our threads in check. I would propose that we get folks onto a Slack channel, but we've also already been invited onto at least one FFBE based Discord channel. Both of these seem pretty cross platform, I only suggest Slack because I already use it for communication in two other areas of my life and it's nice to keep things simple.

What are y'all's thoughts on this issue?

**Comment by kastyr1984** [comment]
I don't mind giving Discord a shot and if I don't think it lives up to
Slack I'll make a case for switching at that point.

**Comment by Mcgillby** [comment]
Im okay with anything, I used to use LINE app

**Comment by Kawoxux** [comment]
am happy with that

Discord invite again:
https://discord.gg/SRCfFcJ

**Comment by Mcgillby** [comment]
Ill sign up in the morning

**Comment by Kawoxux** [comment]
Hey @Mcgillby , don't forget to join us on Discord :D
