### ISSUE TITLE
Should we recommend Continuous Auto Battle be turned off?

### ISSUE THREAD

**Issue by kastyr1984** [MacroTeam/FFBE-Macros#4]
This seems like it will make every macro safer. What are the drawbacks? Will this cause any breakage to other types of macros?

**Comment by Mcgillby** [comment]
Only on the lapis refill builds. its fine for any other build because you dont run the risk of lapis revive. which is the main issue causing large lapis loss for pwnlogy ULTIMATE TM BUILD users. The buttons for revive and refill are in the same location, therefore if the macro does not refill, it will not revive. The worst possible outcome for having an auto press in a no refill macro would be having your nrg run down to zero or remain defeated/unrevived in a dungeon with too strong of mobs for the units. No risk of lapis loss in no refill version, assuming no touchpoints line up with the refill or revive button popups.

**Comment by kastyr1984** [comment]
Lapis revive presses can be safely eliminated in their entirety, but if you're into a loop in a dungeon that you can win battles in, Continuous Auto Battle will burn through lapis MUCH faster than an AUTO press without Continuous Auto Battle.

**Comment by Mcgillby** [comment]
yes, Continuous AUTOBATTLE OFF should be recommended for all builds, not only for safety but for proper function of the scripts

**Comment by Mcgillby** [comment]
Like I said tho, without a lapis refresh press, no risk of lapis loss, continuous auto battle is not ideal for most if not all situations, but having an auto press is mostly safe as long as not a refill type macro.

**Comment by kastyr1984** [comment]
You said lapis revive before, which we have to differentiate from lapis
refill. If you wipe and it asks you to continue, that's a lapis revive.
Lapis refill is when you hit 0 and you reup for Lapis. Both can burn a lot
of Lapis but a faulty revive is quadruple trouble in a dungeon that will
wipe your TM farmers.

No continuous auto battle at least slows these processes in almost every
case.

**Comment by Mcgillby** [comment]
As for the question
> Will this cause any breakage to other types of macros?

I dont think any of the macros rely on or even recommend using this Continuous Auto-Battle ON. I cannot think of any situation where turning it OFF would cause breakage to any existing macro, however turning it on might and as such I think its very important to recommend in our threads that it be turned OFF. I recommend it in all my Android Macro threads.

**Comment by kastyr1984** [comment]
I think explorations rely on auto battle to some extent. Maybe not enough
to cause breakage with continuous off.

**Comment by Mcgillby** [comment]
i just looked at the exploration build. they work on a principal on clicking in upper right then bottom left, you can move the touch points to avoid re_entry to the game after a crash.. it actually will go to either squareenix webpage or customer service haha

**Comment by Mcgillby** [comment]
going to bed now.. ttyl

**Comment by Mcgillby** [comment]
if your in the exploration, you would want it to re enter to finish?, or maybe not because it would cause the script too desync anyways.

**Comment by Mcgillby** [comment]
you just gave me a good idea on how we can fix the exploration macros, or make new ones. I think Autobattle on would maybe be worth using on explorations because you could get more control of the inputs without having to worry about your units attacking.

**Comment by ghost** [comment]
I say that it ultimately depends of what the macro is meant to do. Continuous auto battle is a godsend for exploration quests, since old exploration macros would relay almost entirely on the "down-left, up-right" cycle that continuosly pressed auto to automatize battles. For tm farming, security-wise it would be better to turn it off, since it's not used.

**Comment by kastyr1984** [comment]
If it's not continuous auto battle, would the explore macros still hit auto often enough to basically accomplish the same thing?

**Comment by ghost** [comment]
Yes, the old macros by pwnology were based on a 2 seconds cycle of down-left=auto, upper right for combat purposes.

**Comment by kastyr1984** [comment]
Considering this question merged into ticket #8, with an answer of "Yes, we should encourage people to disable continuous auto battle and assume they've done so in future sanctioned development.
