### ISSUE TITLE
Mcgillby conversion issue

### ISSUE THREAD

**Issue by kastyr1984** [MacroTeam/FFBE-Macros#6]
There was a problem in the master branch with some of mcgillby's converted macros. They needed to be assigned --in-x and --in-y values (which is common with MEmu macros). Output looks pretty good now, but needs to be tested.

**Comment by Mcgillby** [comment]
Just tested NOX TMFarming720. Its better but it is still inverted. Its in the correct area but is mirrored and the inputs are on the left side instead of the right if you understand that? like before it was sideways, now its not sideways and the touchpoints are correct except its hitting unit 4/6 instead of 1/3 and its going for the refresh click on the left instead of the right.. hope that is enough info.. if not ill make a video.

**Comment by Mcgillby** [comment]
Im getting the hang of navigating this site. Ill test the other versions and see if there are any faults. The speed of the MEmu to NOX conversion TMRefill720 is incredible. It will be a huge improvement from my original NOX script. The Y Values seem correct. The X values are backwards/mirrored.

**Comment by curunoir** [comment]
If I remember correctly I had similar issues with HiroMacro scripts running on a rooted phone.

**Comment by kastyr1984** [comment]
Got it. I'll take a look when I wake up. Can you make sure you haven't changed any resolution settings on your Memu machine from default?

**Comment by kastyr1984** [comment]
@curunoir, think this is the issue that you were having a few weeks ago? I think there is an error in my screen flip handling, but the only reason I think this is happening here is because I think @Mcgillby has non-standard Memu resolution settings in some of these macros and since Memu doesn't record the resolution settings inside the file itself it's impossible to differentiate except when the y-axis isn't inverse and shit just breaks all the time.

The better thing to do right now for everyone is to leave resolution at default settings so that macros can be standardized as they've been for months now. Even when I fix this bug in the convertMacros code, it's impossible to know if someone has changed the resolution in their Memu settings without them explicitly saying so, and it fucks everything up.

**Comment by curunoir** [comment]
I agree that a standard resolution should be the base of devs/fixes. His issue reminds me of mine with HiroMacro which was setting origin point on top right corner of my device, so I fixed my issue by converting standard pwnology nox scripts with a little math (720 minus the original x value).

The thing is I'm not sure if this issue is related to speficially HiroMacro on my device. Luckily my device has in theory same resolution as standard Nox and Memu. I don't know if I should open another issue, maybe the question is also if you target mainly emulators script or more wisely every device with macro abilities. (sorry for my english btw)

**Comment by kastyr1984** [comment]
We should probably open an issue on the convertMacros Github page. I have a
couple ideas of where the issue may be coming from, actually, but if you
could give me a sample line to test with and it's expected output I could
probably accelerate a fix on my end.

**Comment by kastyr1984** [comment]
I went ahead and set --flip-x to see if that fixes it.

**Comment by kastyr1984** [comment]
Appears to have been fixed with incorporation of --flip-y into the conversion script command line. Will continue to monitor issue but closing ticket for now.

**Comment by Mcgillby** [comment]
how do i know when you message. can i get a phone app?

**Comment by Mcgillby** [comment]
ill go test now, thanks

**Comment by kastyr1984** [comment]
There should be a notification button on the panel on the right side of the github issue or pull request page that you can use to subscribe to notifications for ones you want to follow.
